### ISSUE TITLE
It's a nice theme - will it be getting a little love for HTML?

### ISSUE THREAD

**Issue by rcrooks** [tomasz-lisowski/theme-ilk#1]
HI @tomasz-lisowski - I like theme a lot, but since I write a fair amount of HTML code, I think it could use a little more color variation there.

Thanks for considering!

**Comment by tomasz-lisowski** [comment]
I'm open for any additions. Can you let me know what changes in particular you would like to see? Perhaps, which elements need improvement in color variation?
I'm glad you like my theme :)

**Comment by rcrooks** [comment]
Thank you! Tag names mainly - something darker, different from text - I think the green you use for function names or the blue for object properties would do nicely, but I'll leave the color choice to your excellent eyes.

**Comment by tomasz-lisowski** [comment]
I made them blue to avoid conflicts with HTML constants like `&quot` or constants in CSS like `#ccc` which are of course highlighted in green. This change will also highlight these tags in CSS, JSX, TSX, and any other language that uses tags.

Here is the commit: 960192877c8f27f8e87ebe5e807daf23c92b5621

**Comment by rcrooks** [comment]
Nice - thanks so much!
